<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <Version>1.4.1</Version>
    <FileVersion>1.4.1.0</FileVersion>
    <AssemblyVersion>1.4.1.0</AssemblyVersion>
    <InformationalVersion>1.4.1</InformationalVersion>
    <Product>DnsSwitcher</Product>
    <Authors>Regstar2</Authors>
    <RepositoryUrl>https://github.com/Regstar2/DnsSwitcher</RepositoryUrl>
  </PropertyGroup>
</Project>
