using System.Globalization;
using DnsSwitcher.Infrastructure.Windows.Configuration;

namespace DnsSwitcher.Infrastructure.Windows.Presentation;

public sealed class AppLocalizer(AppLanguage configuredLanguage)
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AppTitle"] = "DnsSwitcher",
        ["ProfilesHeader"] = "Profiles",
        ["AdapterAndAppHeader"] = "Adapter and App",
        ["CurrentStatusHeader"] = "Current Status",
        ["SelectedProfileHeader"] = "Selected Profile",
        ["ApplyButton"] = "Apply",
        ["ResetButton"] = "Reset",
        ["TestDnsButton"] = "Test DNS",
        ["TestSitesButton"] = "Test Sites",
        ["ReloadButton"] = "Reload",
        ["SettingsButton"] = "Settings",
        ["OpenConfigButton"] = "Open Config",
        ["OpenLogsButton"] = "Open Logs",
        ["StartWithWindowsCheckBox"] = "Start tray with Windows",
        ["CloseToTrayCheckBox"] = "Continue in tray on close",
        ["LanguageLabel"] = "Language:",
        ["LanguageSystem"] = "System",
        ["LanguageEnglish"] = "English",
        ["LanguageRussian"] = "Russian",
        ["SettingsWindowTitle"] = "Settings",
        ["SettingsLanguageHeader"] = "Language",
        ["SettingsBehaviorHeader"] = "Behavior",
        ["SettingsThemeHeader"] = "Theme",
        ["ThemeLabel"] = "Theme:",
        ["ThemeFollowsSystemText"] = "Theme follows the Windows system setting.",
        ["ThemeCurrentFormat"] = "Current theme: {0}",
        ["ThemeSystemValue"] = "System",
        ["ThemeDarkValue"] = "Dark",
        ["ThemeLightValue"] = "Light",
        ["SaveButton"] = "Save",
        ["CancelButton"] = "Cancel",
        ["CurrentProfileLabel"] = "Current profile:",
        ["ConfigActiveProfileLabel"] = "Config active profile:",
        ["SelectedAdapterLabel"] = "Selected adapter:",
        ["DnsModeLabel"] = "DNS mode:",
        ["AgentServiceLabel"] = "Agent service:",
        ["AgentAvailableLabel"] = "Agent available:",
        ["Ipv4Label"] = "IPv4 DNS:",
        ["Ipv6Label"] = "IPv6 DNS:",
        ["ProfileLabel"] = "Profile:",
        ["SummaryLabel"] = "Summary:",
        ["TagsLabel"] = "Tags:",
        ["ReadyStatus"] = "Ready.",
        ["WorkingStatus"] = "Working...",
        ["UiLoadedStatus"] = "UI loaded.",
        ["ReloadedStatus"] = "Configuration and status reloaded from disk and system state.",
        ["AdapterChangedStatus"] = "Adapter selection changed.",
        ["SelectProfileFirstError"] = "Select a DNS profile first.",
        ["ResetSuccess"] = "DNS settings were reset to DHCP.",
        ["MinimizeToTrayEnabled"] = "Continue in tray on close is enabled.",
        ["MinimizeToTrayDisabled"] = "Continue in tray on close is disabled.",
        ["AutostartEnabled"] = "Tray will start with Windows.",
        ["AutostartDisabled"] = "Tray autostart was disabled.",
        ["OpenedConfigFolder"] = "Opened config folder.",
        ["OpenedLogsFolder"] = "Opened logs folder.",
        ["SettingsSaved"] = "Settings saved.",
        ["MainWindowClosedToTray"] = "UI was closed. Tray remains running.",
        ["AppliedProfileFormat"] = "Applied profile '{0}'.",
        ["YesValue"] = "Yes",
        ["NoValue"] = "No",
        ["AutomaticDhcpStatus"] = "Automatic / DHCP",
        ["CustomManualDnsStatus"] = "Custom manual DNS",
        ["CustomMixedDnsStatus"] = "Custom mixed DNS",
        ["UnknownValue"] = "<unknown>",
        ["TrayExecutableNotFound"] = "DnsSwitcher.Tray.exe could not be found.",
        ["UiExecutableNotFound"] = "DnsSwitcher.Ui.exe could not be found.",
        ["NoneValue"] = "<none>",
        ["DnsTestTitle"] = "DNS Test",
        ["SiteTestTitle"] = "Site Test",
        ["AvailableProfile"] = "Available profile",
        ["CurrentFlag"] = "current",
        ["ConfiguredFlag"] = "configured",
        ["AutomaticNoDefaultAdapter"] = "Automatic (no default adapter)",
        ["AutomaticAdapterFormat"] = "Automatic ({0})",
        ["ActiveLabel"] = "active",
        ["GatewayLabel"] = "gateway",
        ["PhysicalLabel"] = "physical",
        ["LoopbackLabel"] = "loopback",
        ["DnsSwitcherTrayTitle"] = "DnsSwitcher",
        ["TrayOpenUi"] = "Open UI",
        ["TrayStatusLoading"] = "Status: loading...",
        ["TrayAdapterLoading"] = "Adapter: loading...",
        ["TrayEnableDns"] = "Enable DNS",
        ["TrayDisableDns"] = "Disable DNS",
        ["TraySwitchNext"] = "Switch Next",
        ["TrayTests"] = "Tests",
        ["TrayTestDns"] = "Test DNS",
        ["TrayTestSites"] = "Test Sites",
        ["TrayShowProfiles"] = "Show Profiles",
        ["TraySettings"] = "Settings",
        ["TrayShowNotifications"] = "Show notifications",
        ["TrayShowAdapterName"] = "Show adapter name",
        ["TrayExit"] = "Exit",
        ["TrayBusyStatus"] = "Status: working...",
        ["TrayErrorStatus"] = "Status: error",
        ["TrayHiddenAdapter"] = "Adapter: hidden",
        ["TrayProfilesUnavailable"] = "Unable to load profiles",
        ["TrayNoStaticProfiles"] = "No static DNS profiles",
        ["TrayDnsEnabledFormat"] = "DNS enabled: {0}",
        ["TrayDnsDisabled"] = "DNS disabled. DHCP is now active.",
        ["TrayDnsSwitchedFormat"] = "DNS switched: {0}",
        ["TrayStatusLabel"] = "Status",
        ["TrayAdapterLabel"] = "Adapter",
        ["TrayModeLabel"] = "Mode",
        ["TrayMatchedProfileLabel"] = "Matched profile",
        ["TraySelectedProfileLabel"] = "Selected profile",
        ["TrayIpv4Label"] = "IPv4 DNS",
        ["TrayIpv6Label"] = "IPv6 DNS",
        ["NoAdapterSelected"] = "no adapter selected",
        ["ActiveSuffix"] = "active",
        ["SelectedSuffix"] = "selected",
        ["DhcpStatus"] = "DHCP",
        ["ManualDnsStatus"] = "Manual DNS",
        ["MixedDnsStatus"] = "Mixed DNS",
        ["UnknownStatus"] = "Unknown",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["AppTitle"] = "DnsSwitcher",
        ["ProfilesHeader"] = "Профили",
        ["AdapterAndAppHeader"] = "Адаптер и приложение",
        ["CurrentStatusHeader"] = "Текущий статус",
        ["SelectedProfileHeader"] = "Выбранный профиль",
        ["ApplyButton"] = "Применить",
        ["ResetButton"] = "Сброс",
        ["TestDnsButton"] = "Тест DNS",
        ["TestSitesButton"] = "Тест сайтов",
        ["ReloadButton"] = "Обновить",
        ["SettingsButton"] = "Настройки",
        ["OpenConfigButton"] = "Открыть конфиг",
        ["OpenLogsButton"] = "Открыть логи",
        ["StartWithWindowsCheckBox"] = "Запускать tray вместе с Windows",
        ["CloseToTrayCheckBox"] = "Оставлять tray при закрытии окна",
        ["LanguageLabel"] = "Язык:",
        ["LanguageSystem"] = "Системный",
        ["LanguageEnglish"] = "English",
        ["LanguageRussian"] = "Русский",
        ["SettingsWindowTitle"] = "Настройки",
        ["SettingsLanguageHeader"] = "Язык",
        ["SettingsBehaviorHeader"] = "Поведение",
        ["SettingsThemeHeader"] = "Тема",
        ["ThemeLabel"] = "Тема:",
        ["ThemeFollowsSystemText"] = "Тема подстраивается под системную тему Windows.",
        ["ThemeCurrentFormat"] = "Текущая тема: {0}",
        ["ThemeSystemValue"] = "Системная",
        ["ThemeDarkValue"] = "Тёмная",
        ["ThemeLightValue"] = "Светлая",
        ["SaveButton"] = "Сохранить",
        ["CancelButton"] = "Отмена",
        ["CurrentProfileLabel"] = "Текущий профиль:",
        ["ConfigActiveProfileLabel"] = "Профиль в конфиге:",
        ["SelectedAdapterLabel"] = "Выбранный адаптер:",
        ["DnsModeLabel"] = "Режим DNS:",
        ["AgentServiceLabel"] = "Сервис агента:",
        ["AgentAvailableLabel"] = "Агент доступен:",
        ["Ipv4Label"] = "IPv4 DNS:",
        ["Ipv6Label"] = "IPv6 DNS:",
        ["ProfileLabel"] = "Профиль:",
        ["SummaryLabel"] = "Сводка:",
        ["TagsLabel"] = "Теги:",
        ["ReadyStatus"] = "Готово.",
        ["WorkingStatus"] = "Выполняется...",
        ["UiLoadedStatus"] = "UI загружен.",
        ["ReloadedStatus"] = "Конфиг и статус перечитаны с диска и из системы.",
        ["AdapterChangedStatus"] = "Выбор адаптера изменён.",
        ["SelectProfileFirstError"] = "Сначала выбери DNS-профиль.",
        ["ResetSuccess"] = "Настройки DNS сброшены на DHCP.",
        ["MinimizeToTrayEnabled"] = "Tray при закрытии окна включён.",
        ["MinimizeToTrayDisabled"] = "Tray при закрытии окна выключен.",
        ["AutostartEnabled"] = "Tray будет запускаться вместе с Windows.",
        ["AutostartDisabled"] = "Автозапуск tray отключён.",
        ["OpenedConfigFolder"] = "Папка конфига открыта.",
        ["OpenedLogsFolder"] = "Папка логов открыта.",
        ["SettingsSaved"] = "Настройки сохранены.",
        ["MainWindowClosedToTray"] = "Окно закрыто. Tray продолжает работать.",
        ["AppliedProfileFormat"] = "Профиль '{0}' применён.",
        ["YesValue"] = "Да",
        ["NoValue"] = "Нет",
        ["AutomaticDhcpStatus"] = "Автоматически / DHCP",
        ["CustomManualDnsStatus"] = "Свой ручной DNS",
        ["CustomMixedDnsStatus"] = "Свой смешанный DNS",
        ["UnknownValue"] = "<неизвестно>",
        ["TrayExecutableNotFound"] = "Не удалось найти DnsSwitcher.Tray.exe.",
        ["UiExecutableNotFound"] = "Не удалось найти DnsSwitcher.Ui.exe.",
        ["NoneValue"] = "<нет>",
        ["DnsTestTitle"] = "Тест DNS",
        ["SiteTestTitle"] = "Тест сайтов",
        ["AvailableProfile"] = "Доступный профиль",
        ["CurrentFlag"] = "текущий",
        ["ConfiguredFlag"] = "в конфиге",
        ["AutomaticNoDefaultAdapter"] = "Автоматически (нет адаптера по умолчанию)",
        ["AutomaticAdapterFormat"] = "Автоматически ({0})",
        ["ActiveLabel"] = "активен",
        ["GatewayLabel"] = "шлюз",
        ["PhysicalLabel"] = "физический",
        ["LoopbackLabel"] = "loopback",
        ["DnsSwitcherTrayTitle"] = "DnsSwitcher",
        ["TrayOpenUi"] = "Открыть UI",
        ["TrayStatusLoading"] = "Статус: загрузка...",
        ["TrayAdapterLoading"] = "Адаптер: загрузка...",
        ["TrayEnableDns"] = "Включить DNS",
        ["TrayDisableDns"] = "Выключить DNS",
        ["TraySwitchNext"] = "Следующий профиль",
        ["TrayTests"] = "Тесты",
        ["TrayTestDns"] = "Тест DNS",
        ["TrayTestSites"] = "Тест сайтов",
        ["TrayShowProfiles"] = "Показать профили",
        ["TraySettings"] = "Настройки",
        ["TrayShowNotifications"] = "Показывать уведомления",
        ["TrayShowAdapterName"] = "Показывать имя адаптера",
        ["TrayExit"] = "Выход",
        ["TrayBusyStatus"] = "Статус: выполняется...",
        ["TrayErrorStatus"] = "Статус: ошибка",
        ["TrayHiddenAdapter"] = "Адаптер: скрыт",
        ["TrayProfilesUnavailable"] = "Не удалось загрузить профили",
        ["TrayNoStaticProfiles"] = "Нет статических DNS-профилей",
        ["TrayDnsEnabledFormat"] = "DNS включён: {0}",
        ["TrayDnsDisabled"] = "DNS выключен. DHCP активен.",
        ["TrayDnsSwitchedFormat"] = "DNS переключён: {0}",
        ["TrayStatusLabel"] = "Статус",
        ["TrayAdapterLabel"] = "Адаптер",
        ["TrayModeLabel"] = "Режим",
        ["TrayMatchedProfileLabel"] = "Совпавший профиль",
        ["TraySelectedProfileLabel"] = "Выбранный профиль",
        ["TrayIpv4Label"] = "IPv4 DNS",
        ["TrayIpv6Label"] = "IPv6 DNS",
        ["NoAdapterSelected"] = "адаптер не выбран",
        ["ActiveSuffix"] = "активен",
        ["SelectedSuffix"] = "выбран",
        ["DhcpStatus"] = "DHCP",
        ["ManualDnsStatus"] = "Ручной DNS",
        ["MixedDnsStatus"] = "Смешанный DNS",
        ["UnknownStatus"] = "Неизвестно",
    };

    public AppLanguage ConfiguredLanguage { get; } = configuredLanguage;

    public AppLanguage EffectiveLanguage { get; } = ResolveEffectiveLanguage(configuredLanguage);

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        if (TryGet(key, out var value))
        {
            return value;
        }

        return key;
    }

    public string Format(string key, params object[] arguments)
    {
        return string.Format(CultureInfo.CurrentCulture, Get(key), arguments);
    }

    public bool TryGet(string key, out string value)
    {
        var catalog = EffectiveLanguage == AppLanguage.Russian ? Russian : English;
        return catalog.TryGetValue(key, out value!);
    }

    private static AppLanguage ResolveEffectiveLanguage(AppLanguage language)
    {
        if (language != AppLanguage.System)
        {
            return language;
        }

        var systemLanguage = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return string.Equals(systemLanguage, "ru", StringComparison.OrdinalIgnoreCase)
            ? AppLanguage.Russian
            : AppLanguage.English;
    }
}
